version: "3"

# Сервисы
services:

  # Сервис для сервера
  server:
    # Ключевое слово "build" позволяет задать путь к файлу Dockerfile, который нужно использовать 
    # для создания образа, который позволит запустить сервис
    build: ./server

    # Перенаправление порта на порт компьютера
    ports:
      - 1234:1234

  # Сервис для клиента
  client:
    # Ключевое слово "build" позволяет задать путь к файлу Dockerfile, который нужно использовать 
    # для создания образа, который позволит запустить сервис
    build: ./client

    # Ключевое слово 'network_mode' используется для описания типа сети
    # Тут мы указываем то, что контейнер может обращаться к 'localhost' компьютера
    network_mode: host

    # Ключевое слово 'depends_on' позволяет указывать, должен ли сервис, прежде чем запуститься, ждать, когда 
    # будут готовы к работе другие сервисы
    # Нам нужно, чтобы сервис 'client' дождался бы готовности к работе сервиса 'server'
 
    depends_on:
      - server